EMBEDDING_MODEL_NAME = "intfloat/e5-large-v2"
LLM_MODEL = "Qwen/Qwen2.5-Math-1.5B-Instruct"
COLLECTION_NAME = "math_combined"
QDRANT_PATH = "agentturing/database/qdrantdb"
DATA_PATH = "agentturing/database/knowledge_base"